version: '3'
services:
  app:
    build: PokeAPIwMySQL
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/pokedb?useSSL=false&allowPublicKeyRetrieval=true
      DB_USER_NAME: root
      DB_PASSWORD: rootpassword

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=pokedb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: